# used to save files data generated by our program into our disk ths we write files
# to store keywords in our mails to figure out what keyword makes an email a spam file
# hdd and sdd files are very slow for this thus file io is to temporary load programs into ram memory for faster execution and all its content is lost when the program is terminated to persistently store the data as well

f = open("file.txt") #this is by default ("file.txt", "r") which means by default read the files and to write we use "w"
data = f.read()
print(data)
f.close() # compulsory to close a file we open to tell the computer that we have taken the needed data and now we dont want to read the file further
